pluginManagement {
    includeBuild("build-logic")
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'khezy-kit'

includeBuild("core/state-machine-core")
includeBuild("core/ast-expression-core")
includeBuild("core/dynamic-form-core")

includeBuild("storage/storage-api")
includeBuild("storage/storage-fs")

includeBuild("utils/string-util")
includeBuild("utils/dynamic-object")
includeBuild("utils/clone-util")
includeBuild("utils/pluginlib")

includeBuild("securities/data-masker")

includeBuild("templates/simple-prompt-template")